### ISSUE TITLE
panic: resource temporarily unavailable

### ISSUE THREAD

**Issue by PC-Admin** [application-research/edge-urid-playbook#2]
Ran into the same bug a few times now with this playbook (hooray, consistency!):
```
Jul 14 07:53:42 prod-ehi-edge-urid03 systemd[1]: Started Edge Daemon Service.
Jul 14 07:53:42 prod-ehi-edge-urid03 edgeurid[253627]: OS: linux
Jul 14 07:53:42 prod-ehi-edge-urid03 edgeurid[253627]: Architecture: amd64
Jul 14 07:53:42 prod-ehi-edge-urid03 edgeurid[253627]: Hostname: prod-ehi-edge-urid03
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: Public IP: 23.227.172.66
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: Starting Edge daemon...
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: Setting up the Edge node... 
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: cfg.Node.Repo is:  /mnt/mfs/services/whypfs/edge-urid
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: cfg.Node.DsRepo is:  /mnt/mfs/services/whypfs/edge-urid-ds
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: panic: resource temporarily unavailable
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: goroutine 1 [running]:
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/application-research/edge-ur/core.NewEdgeNode({0x1f0b070, 0xc000042190}, {{{0xc000046052, 0xd}, {0xc000044061, 0x33}, {0x0, 0x0}, {0xc00004c007, 0x6c}, ...}, ...})
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /usr/local/src/edge/core/node.go:82 +0x5b9
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/application-research/edge-ur/cmd.DaemonCmd.func1(0xc000157b80?)
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /usr/local/src/edge/cmd/daemon.go:59 +0x52b
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/urfave/cli/v2.(*Command).Run(0xc000157b80, 0xc0000f5340, {0xc0006e8820, 0x2, 0x2})
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /var/lib/arg-edge/workspace-go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/command.go:274 +0xa42
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/urfave/cli/v2.(*Command).Run(0xc000157e40, 0xc0000f5280, {0xc000040180, 0x3, 0x3})
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /var/lib/arg-edge/workspace-go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/command.go:267 +0xc97
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/urfave/cli/v2.(*App).RunContext(0xc00017c5a0, {0x1f0b070?, 0xc000042190}, {0xc000040180, 0x3, 0x3})
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /var/lib/arg-edge/workspace-go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:332 +0x616
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: github.com/urfave/cli/v2.(*App).Run(...)
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /var/lib/arg-edge/workspace-go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:309
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]: main.main()
Jul 14 07:53:43 prod-ehi-edge-urid03 edgeurid[253627]:         /usr/local/src/edge/main.go:34 +0x1cd
Jul 14 07:53:43 prod-ehi-edge-urid03 systemd[1]: edge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 14 07:53:43 prod-ehi-edge-urid03 systemd[1]: edge.service: Failed with result 'exit-code'.
Jul 14 07:53:43 prod-ehi-edge-urid03 systemd[1]: edge.service: Scheduled restart job, restart counter is at 5.
Jul 14 07:53:43 prod-ehi-edge-urid03 systemd[1]: Stopped Edge Daemon Service.
```

I'm not sure what resource it's referring to but the error line to follow seems to be `panic: resource temporarily unavailable`.

**Comment by PC-Admin** [comment]
the contents of the folders it was querying just before this error:
```
ubuntu@prod-ehi-edge-urid03:~$ ls /mnt/mfs/services/whypfs/edge-urid-ds
000001.log  CURRENT  LOCK  LOG  MANIFEST-000000
ubuntu@prod-ehi-edge-urid03:~$ ls /mnt/mfs/services/whypfs/edge-urid
blocks
```

**Comment by PC-Admin** [comment]
Scratch that, I was just holding it wrong. Reverting this change gets rid of the error:

https://github.com/application-research/edge-urid-playbook/compare/main...catchup#diff-b699279d2d0a4d86ccfe92b9a38adf6224169f045a592b81f382ba9dbf1dc912R14

**Comment by PC-Admin** [comment]
Okay the bug is still appearing frequently and I suspect that something else is causing this! :S

Seeing the exact same bug on prod-ehi-edge-urid01 and prod-ehi-edge-urid04 after trying to deploy them...
